#version 450
#extension GL_GOOGLE_include_directive : enable

#include "../include/709.h"

layout(std430, binding = 0) buffer Buf 
{
   uint output_buffer[ ];
};

layout (local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

layout (push_constant) uniform PushConstants {
    ivec4 vkd_offset;
    ivec2 _size;
} push;


void main() 
{
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy) + push.vkd_offset.xy;
    
    int ind = (push._size.x / 4) * coord.y + coord.x;
    output_buffer[ind] = packUnorm4x8(vec4(1.0, 1.0, 1.0, 1.0));//packUnorm4x8(vec4(inp.x, inp2.x, inp3.x, inp4.x));
}


