
#version 450

// Binding 0 : Position storage buffer
layout(binding = 0, rgba32f) uniform image2D finalTex;

layout (local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

#define M_PI           3.14159265358979323846  /* pi */

layout (push_constant) uniform PushConstants {
    ivec4 vkd_offset;
    vec4 _blank;
} push;

void main() 
{
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy) + push.vkd_offset.xy;
    imageStore(finalTex, coord, push._blank);
}
